### ISSUE TITLE
python path missing - symlink needed

### ISSUE THREAD

**Issue by jayramr** [flywheel-apps/Gear-Building-Tutorial#2]
https://github.com/flywheel-apps/Gear-Building-Tutorial/blob/e8209e51817aa92edce7728e1283d7884aad95fa/Dockerfile#L10

Hello,

Please include below in the Docker file as getting error ->```bash: line 1: python: command not found``` 
```
RUN ln -s /usr/bin/python3 /usr/bin/python
```

Thanks
Jay

**Comment by mlewis1973** [comment]
another solution
RUN apk add --update bash \

**Comment by dpark6060** [comment]
@jayramr This docker file builds and launches python just fine for me.  The issue is that you're calling "python", not "python3".  This dockerfile is designed to run only with the gear building tutorial, which calls python3 explicitly.  If your code calls python, then please feel free to symlink in your own docker images.
